(SIMP-8839) Remove EL6 from pupmod-simp-ima
simp/pupmod-simp-ima pull request #23
Opened 2020-12-17 22:45 UTC by op-ct

This patch removes EL6 as a supported OS in `metadata.json`, Hiera YAML
files and from the beaker acceptance tests and nodesets.

SIMP-8861 #close
[SIMP-8839] #comment Removed EL6 from pupmod-simp-ima
[SIMP-8489] #comment Updated pupmod-simp-ima GLCI pipeline to Puppet 6.18
[SIMP-8923] #comment Renamed 'sanity' to 'releng' in pupmod-simp-ima

2020-12-18 13:47 UTC, lnemsick-simp commented on spec/acceptance/nodesets/default.yml
> +      # roles migrated from now-removed el6 node(s):
comment is incorrect

2020-12-18 13:47 UTC, lnemsick-simp commented on spec/acceptance/nodesets/oel.yml
> +      # roles migrated from now-removed el6 node(s):
comment is incorrect

2020-12-18 13:56 UTC, lnemsick-simp reviewed
Shouldn't the files/import_ima_rules SystemV file be removed and the logic that uses it in manifests/policy.pp:?

2020-12-18 13:58 UTC, lnemsick-simp requested changes
* automated role merging left inappropriate comments
* Unless a follow-on PR to address code changes is expected, the SystemV artifacts/logic should be removed here.

2020-12-22 20:31 UTC, trevor-vaughan approved these changes

2020-12-22 20:32 UTC, merged